### ISSUE TITLE
How to install this in local pc??

### ISSUE THREAD

**Issue by nithinreddyy** [tecoholic/ner-annotator#31]
Can you please post the inputs to install this in local pc?

**Comment by tecoholic** [comment]
@nithinreddyy If you have a Linux computer, you can install it locally as an app. See here https://github.com/tecoholic/ner-annotator/discussions/30

Otherwise you can setup a "Development" copy if you are familiar with NodeJS frontend development as mentioned in the Readme.

If both of the options seem unsuitable, just use it from the website https://tecoholic.github.io/ner-annotator/
