### ISSUE TITLE
Is there a way to import annotations.json, in case I want to revisit the tags?

### ISSUE THREAD

**Issue by Curiosity007** [tecoholic/ner-annotator#69]
Is there a way to import annotations.json, in case I want to revisit the tags? 
Otherwise I have to retrain the whole document again, with similar tags

**Comment by alvi-khan** [comment]
This is currently being tracked in #62. The changes haven't been fully tested (which is why it's not merged yet), but if you're comfortable with building the app from the source code you can check out [this fork](https://github.com/alvi-khan/ner-annotator/tree/import-annotations). I've been using the Windows build for a few weeks now and haven't run into any issues yet.

**Comment by Curiosity007** [comment]
> This is currently being tracked in #62. The changes haven't been fully tested (which is why it's not merged yet), but if you're comfortable with building the app from the source code you can check out [this fork](https://github.com/alvi-khan/ner-annotator/tree/import-annotations). I've been using the Windows build for a few weeks now and haven't run into any issues yet.

Hi, can not access that link. Can you please reshare?
